### ISSUE TITLE
https://ci.eclipse.org/rcptt/job/master/ fails and seems to have no timeout

### ISSUE THREAD

**Issue by fredg02** [eclipse-rcptt/org.eclipse.rcptt#94]
The build job description states:

> This should always be green. If it is not, its panic time.

The last successful build was on October 31, 2024. I suppose it's panic time then? :grimacing: 

https://ci.eclipse.org/rcptt/job/master/1951/ was hanging for more than a day. Please add a timeout to your Jenkinsfile, e.g.:

```
options {
  timeout(time: 8, unit: 'HOURS')
}
```

**Comment by basilevs** [comment]
There are timeouts within Maven projects. They did not work due to a Jenkins bug though.

```
Cannot contact rcptt-build-and-deploy-agent-3.5.4-h09xv-x82zl: java.lang.InterruptedException
wrapper script does not seem to be touching the log file in /home/jenkins/agent/workspace/master@tmp/durable-701c1da4
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by basilevs** [comment]
It time to change job description. We almost always have a failed test.

**Comment by fredg02** [comment]
> There are timeouts within Maven projects. They did not work due to a Jenkins bug though.

That's not a Jenkins bug. Jenkins proposes a workaround for an issue where either the file system has an issue or the build does not write anything to the log for a long time. In this case, it seems to be the latter.
